server:
  port: 8040

spring:
  application:
    name: affcar
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/affcar
    username: wk-projects
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
