server:
  port: 8040

spring:
  application:
    name: affcar
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/affcar
    username: wk-projects
    password: admin
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/config/liquibase/master.xml

axeane:
  security:
    authentication:
      jwt:
        secret: my-secret-token-to-change-in-production
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
